// Source inventory, not a promise that a provider is connected on this host.
import {readFile, readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
export const capabilities = {
  schemaVersion: 1,
  availability: 'Query the referenced status endpoint at runtime; source presence is not readiness.',
  domains: [
    {id:"workspaces",version:1,ui:"sidebar/workspaces",sources:["wrapper/workspace-directory.mjs","wrapper/workspace-onboarding.mjs","wrapper/ui/workspace-settings.tsx"],contract:"wrapper/surfaces/workspaces.md",status:"GET /api/workspaces",backend:"Optional specializations in existing project folders; fresh AGENTS.md context and idempotent native onboarding chat"},
    {id:"firma",version:1,migration:"Additive firma.json receipts and optional chat assignment; no existing company files are changed at install.",ui:"firma",sources:["wrapper/firma.mjs","wrapper/firma-catalog.mjs","wrapper/ui/firma.tsx","wrapper/ui/firma.css"],contract:"wrapper/surfaces/firma.md",status:"GET /api/firma",backend:"Scoped native chats, current source evidence and version-bound user confirmation"},

    {id:'ai-maintenance',ui:'settings/engines',sources:['system/ai-catalog.mjs','wrapper/ai-maintenance.mjs','wrapper/ui/ai-maintenance.tsx'],contract:'wrapper/WORKERS.md',status:'/api/ai-maintenance',backend:'existing core maintenance tick, managed CLI versions, public model catalog and durable notifications'},
    {id:'github',ui:'settings/connections',sources:['core/github.py','wrapper/ui/github-connection.tsx'],contract:'docs/GITHUB.md',status:'/api/github/status',backend:'GitHub App Device Flow and existing encrypted provider vault'},
    {id:'updates',ui:'settings/updates',sources:['core/product_updates.py','core/update_checks.py','core/update_operator.py','wrapper/ui/product-updates.tsx'],contract:'docs/UPDATES.md',status:'/api/system/updates',backend:'existing scheduler, durable core journal, isolated checks and separately installed local operator'},
    {id:'contributions',ui:'settings/updates/contributions',sources:['core/contributions.py'],contract:'docs/UPDATES.md',status:'/api/system/contributions',backend:'private neutral source snapshots, read-only comparison and separate development candidates'},

    {id:'device-connections', version:'1.0.0', dataVersion:1, ui:'settings/connections', sources:['core/devices.py','core/device_network.py','core/device_api.py','core/mcp.py','wrapper/shared-memory.mjs','wrapper/ui/device-connection.tsx','wrapper/ui/device-connection.css'], contract:'docs/DEVICES.md', status:'/api/devices and /api/network/status', backend:'FastAPI, native adb, Samsung WebSocket and native Tailscale CLI', migration:'Additive devices/registry-v1 and devices/network-v1 records; unknown versions refused; external Serve rules must be stopped before rollback'},
    {id:"work-evidence", ui:"settings/service", sources:["wrapper/ui/work-evidence.tsx","wrapper/ui/work-evidence.mjs","wrapper/ui/work-evidence.css"], contract:"wrapper/surfaces/work-evidence.md", status:"explicit fictional demo only", backend:"none; real time capture and scoped A2A planned"},
    {id:'crm-core', sources:['core/crm.py','core/crm_schema.py','core/crm_models.py','core/crm_mapping.py','core/crm_api.py','core/mcp.py'], contract:'docs/CRM.md', status:'/api/crm/schema', backend:'FastAPI and existing SQLite; no connector sync enabled'},
    {id:'planner', sources:['wrapper/ui/planner.tsx','wrapper/ui/planner.css','wrapper/ui/planner-dates.mjs','wrapper/ui/planner-data.mjs','wrapper/ui/planner-demo.ts'], contract:'wrapper/surfaces/today.md', status:'interactive concept with live CRM reads and existing notifications', backend:'existing CRM and notification APIs; calendar, weather and briefing feeds pending'},
    {id:'source-privacy', sources:['core/source_work.py','scripts/source-work.py','scripts/security-scan.py','scripts/source-sync.py','scripts/verify-source-adoption.mjs','scripts/install-git-hooks.mjs','backend/company-base.mjs','system/source-policy.json'], contract:'docs/CODE-SYNC.md', status:'npm run source:check; local hooks require source:setup', backend:'local Git CLI; GET /api/system/source-work', surface:null},
    {id:'inbox', sources:['wrapper/ui/inbox.tsx','wrapper/ui/inbox.css','core/mail.py','core/provider_vault.py'], contract:'wrapper/surfaces/inbox.md', status:'/api/mail/accounts', backend:'core/mail.py'},
    {id:'chat', sources:['wrapper/ui/app.jsx','wrapper/server.mjs'], contract:'wrapper/surfaces/chat.md'},
    {id:'speech', sources:['wrapper/ui/message-speech.tsx','wrapper/ui/speech-playback.mjs','wrapper/speech.mjs','system/runtime-assets.mjs','requirements-speech.lock','scripts/setup-system.mjs'], contract:'wrapper/VOICE.md', status:'/api/speech/status'},
    {id:'dictation', sources:['wrapper/ui/dictation.jsx','wrapper/ui/dictation-shortcut.mjs','wrapper/ui/dictation-shortcut-settings.jsx','wrapper/dictation.mjs'], contract:'wrapper/DICTATION.md', status:'/api/dictation/status'},
    {id:'connections', sources:['wrapper/ui/connection-catalog.mjs','wrapper/service-catalog.mjs','wrapper/crm-catalog.mjs','wrapper/integrations.mjs'], contract:'wrapper/surfaces/connections.md'},
    {id:'workers', sources:['system/worker-catalog.mjs','wrapper/workers.mjs','wrapper/acp-worker.mjs','wrapper/local-model-catalog.mjs'], contract:'wrapper/WORKERS.md', status:'/api/workers'},
    {id:'jobs', sources:['core/queue.py','core/routines.py','core/notifications.py','core/mcp.py','wrapper/job-notifications.mjs','wrapper/ui/job-notifications.jsx','wrapper/job-templates.mjs'], contract:'wrapper/surfaces/jobs.md', status:'/api/routines/tool (routine_capabilities)', backend:'existing SQLite scheduler'},
    {id:'library', version:3, title:'Ergebnisse', status:'GET /api/library', category:'POST /api/library/category', sources:['wrapper/ui/library.jsx','core/files.py'], contract:'wrapper/surfaces/library.md'},
    {id:'skills', sources:['wrapper/ui/skill-details.jsx'], contract:'wrapper/surfaces/skills.md'},
    {id:'knowledge', sources:['core/knowledge.py','core/memory.py','core/mcp.py'], contract:'docs/CORE.md'},
    {id:'channels', sources:['wrapper/channel-runtime.mjs'], contract:'wrapper/CHANNELS.md'},
    {id:'settings', sources:['core/settings.py','wrapper/ui/voice-settings.jsx','wrapper/ui/pane-shortcut-settings.jsx','wrapper/ui/pane-shortcuts.mjs'], contract:'wrapper/surfaces/settings.md'},
    {id:'operations', sources:['core/operations.py','core/service.py','core/backups.py','core/restore.py','core/secrets.py'], contract:'docs/OPERATIONS.md'},
  ],
  actions: [
    {id:"workspaces.setup",version:"1.0.0",surface:"sidebar Workspace heading, Plus and project menu",component:"wrapper/ui/workspace-settings.tsx",api:{read:"GET /api/workspaces/definition",save:"POST /api/workspaces/save",open:"POST /api/workspaces/chat"},behavior:"Click-accessible explanation; short native onboarding conversation; revision-checked description editor; stable IDs and paths, shared assistant and company base",contract:"wrapper/surfaces/workspaces.md"},
    {id:"jobs.categories",version:"1.0.0",surface:"jobs list and existing JobForm",component:"wrapper/ui/workspace-settings.tsx",sources:["wrapper/ui/job-categories.mjs"],api:{save:"POST /api/jobs/save",tools:"POST /api/routines/tool"},behavior:"Optional custom category, Allgemein default, independent list filter; category never changes workspace, execution or output location",contract:"wrapper/surfaces/jobs.md"},
    {id:'chat.reader-artifacts',version:'1.1.0',surface:'final answer, below activity and before message actions',component:'wrapper/ui/chat-artifacts.jsx',sources:['wrapper/ui/artifact-content.mjs','wrapper/ui/chat-artifacts.css','wrapper/ui/chat-rich-content.jsx','wrapper/ui/chat-rich-content.mjs','wrapper/ui/tool-content.mjs','wrapper/ui/file-content.jsx'],api:{preview:'GET /api/file/info',open:'GET /api/file/raw'},behavior:'Reader artifacts only; source edits remain in tool history, compact collapsible documents, visible typed generated images with enlargement/download, workspace raster/SVG previews and inert SVG fences, no automatic remote or provider-path fetch, no duplicate inline images or document links; existing file inventory retained',migration:'Presentation only; no data migration or file deletion.',contract:'wrapper/surfaces/chat.md'},
    {id:'chat.native-questions',version:'1.0.1',surface:'chat composer; design reference',component:'wrapper/ui/composer-question.tsx',sources:['wrapper/ui/composer-question.css','wrapper/worker-questions.mjs','wrapper/codex.mjs','wrapper/acp-worker.mjs','wrapper/workers.mjs'],api:{reply:'POST /api/respond',pending:'GET /api/bootstrap'},status:'pending native requests via bootstrap and SSE; provider connection via /api/workers',behavior:'Native Codex user input and ACP form elicitation; compact glass question card, original choices and custom composer text, sequential multiple questions, exact native replies without new turns, preserved ordinary drafts, pending/error/resolved states',migration:'No data migration. Non-secret question receipts use existing tools.json. Resolve or cancel native requests before adapter rollback.',contract:'wrapper/surfaces/chat.md'},
    {id:'weather.current', surface:'settings user; chat start weather card', component:'wrapper/ui/user-preferences.tsx', sources:['wrapper/weather.mjs','wrapper/ui/weather-client.mjs','wrapper/ui/chat-start-data.tsx','wrapper/ui/components/ui/weather-scene.tsx','wrapper/ui/weather-preview.tsx','wrapper/ui/weather-motion.tsx','wrapper/weather-report.mjs'], api:{search:'GET /api/weather/locations',current:'GET /api/weather/current',chat:'POST /api/weather/chat'}, behavior:'Public Open-Meteo, GeoNames city selection, persisted coordinates, 10-minute server cache and visible-start refresh; timestamp and explicit errors; day/night, daily extremes, atmospheric weather scenes in the existing fan; local motion preference; warning visualization is a labelled preview only; layered pointer parallax; configured card opens a new workspace report chat with 7-day data snapshot and context-aware summary, idempotent click retries', contract:'wrapper/surfaces/settings.md'},
    {id:'settings.user-profile', surface:'settings user; weather card', component:'wrapper/ui/user-preferences.tsx', sources:['wrapper/ui/user-profile.mjs'], api:{read:'GET /api/file/text?path=soul%2FUSER.md',save:'POST /api/file/save'}, behavior:'User display name and weather location in workspace soul/USER.md; preserves other Markdown; unconfigured weather card opens settings, configured card opens weather report chat; confirmed coordinates, debounced GeoNames city search via Open-Meteo and weather refresh after save', contract:'wrapper/surfaces/settings.md'},
    {id:'planner.day-chat',surface:'chat start calendar card and existing calendar',component:'wrapper/ui/calendar-card.tsx',sources:['wrapper/ui/calendar-day.mjs','wrapper/calendar-chat.mjs','core/calendar.py'],api:{day:'GET /api/calendar/day',chat:'POST /api/calendar/chat',save:'POST /api/calendar/local/save',remove:'POST /api/calendar/local/delete'},behavior:'Workspace-local calendar with additive storage, source-separated external projections, next appointment countdown, day-report conversation and qualified remaining calendar gaps; no provider writes',contract:'docs/PLANNER.md'},
    {id:'settings.icon-animation', surface:'settings appearance visual; design reference icons', component:'wrapper/ui/icon-motion-setting.tsx', sources:['wrapper/ui/icon-catalog.mjs','wrapper/ui/icon-animation.mjs','wrapper/ui/icon-motion.tsx','wrapper/ui/motion-glyph.tsx','wrapper/ui/icon-motion-preview.tsx','wrapper/ui/appearance.mjs'], api:{settings:'POST /api/settings'}, behavior:'81 original system glyphs with individual finite gestures; persisted hover/press/off; app and OS reduced motion take precedence; real copy confirmation follows clipboard success', contract:'wrapper/surfaces/settings.md'},
    {id:'planner.report-chat', surface:'Heute: Briefings & Ergebnisse', component:'wrapper/ui/planner.tsx', sources:['wrapper/briefing-chat.mjs','wrapper/chat-handoff.mjs','core/notifications.py'], api:{list:'GET /api/planner/results',open:'POST /api/planner/chat'}, behavior:'Latest five completed routine receipts; immutable assistant report snapshot in a reusable conversation; explicit labelled demo reports; no worker turn on open', contract:'wrapper/surfaces/today.md'},
    {id:'settings.agent-animation', surface:'settings appearance visual; agent avatar picker', component:'wrapper/ui/avatar-motion-setting.jsx', sources:['wrapper/ui/avatar.jsx','wrapper/ui/agent-avatars.mjs','wrapper/ui/avatar-motion.mjs','wrapper/ui/appearance.mjs'], api:{settings:'POST /api/settings',identity:'POST /api/identity'}, behavior:'Eight footless SVG faces; shared persisted motion choices; neutral reduced-motion state and visibility pause; expressions are decorative, not status', contract:'wrapper/surfaces/settings.md'},
    {id:'workspace.html-presentation',version:'1.0.0',surface:'right workspace and shared HTML preview',component:'wrapper/ui/html-preview.tsx',sources:['wrapper/html-presentation.mjs'],api:{preview:'GET /api/file/preview'},behavior:'User-controlled enlargement, native fullscreen and marked-slide presentation with return to original document state; no automatic playback or new browsing surface',migration:'Optional presentation channel only; original files unchanged and old preview clients remain valid.',contract:'wrapper/surfaces/library.md'},
    {id:'library.html-preview', version:'1.1.0', surface:'chat HTML links; workspace files; library preview', component:'wrapper/ui/html-preview.tsx', sources:['wrapper/ui/file-content.jsx','wrapper/html-preview.mjs','wrapper/html-presentation.mjs'], api:{preview:'GET /api/file/preview',info:'GET /api/file/info'}, behavior:'Shared sandboxed HTML rendering; responsive compact workspace first; expand same iframe on demand; native fullscreen; opt-in marked slide navigation through a bounded opaque-origin channel; original scroll restored on presentation exit; explicit source/edit mode; embedded assets only; no live file watch', migration:'No file or stored-data changes. New bridge requires updated server; old preview callers and old servers retain plain HTML rendering.', contract:'wrapper/surfaces/library.md'},
    {id:'connections.21st', surface:'settings connections; Design & Medien', component:'wrapper/ui/connection-catalog.mjs', api:{save:'POST /api/connections/save',status:'GET /api/integrations'}, behavior:'Browser link only; setup at https://21st.dev/mcp. External MCP https://21st.dev/api/mcp requires x-api-key; saving the link does not install or authenticate MCP tools.', contract:'wrapper/surfaces/connections.md'},
    {id:'crm.facts', surface:'shared MCP and API; customer forms not yet connected', component:'core/crm_api.py', api:{schema:'GET /api/crm/schema',query:'POST /api/crm/query',propose:'POST /api/crm/proposals',decide:'POST /api/crm/decisions'}, behavior:'Typed workspace entities, per-field sources, proposals before facts, optimistic revisions and incoming-evidence freshness; no autonomous approval or external writes'},
    {id:'jobs.frontend-health',version:'1.0.0',surface:'system jobs and settings',component:'core/frontend_check.py',sources:['core/operations.py','core/settings.py','core/runtime.py','wrapper/ui/system-settings.tsx'],api:{jobs:'GET /api/jobs',status:'GET /api/system/status'},behavior:'Daily 04:15 local delivery checks without an LLM, deferred during active work; existing failure notifications; no automatic code changes or restarts; does not measure client network or rendering',migration:'Additive system.frontend_check defaults true; explicit false persists; no chat or context migration.',contract:'wrapper/surfaces/jobs.md'},
    {id:'jobs.workspace-selection', surface:'jobs list and detail', component:'wrapper/ui/app.jsx#JobForm', sources:['wrapper/ui/jobs-view.mjs','wrapper/storage.mjs','wrapper/worker-models.mjs'], api:{save:'POST /api/jobs/save',run:'POST /api/jobs/run'}, behavior:'User status tabs separate managed system routines; workspace and advertised model/effort persist per job and apply to each new run chat; backup activation validates archive access', contract:'wrapper/surfaces/jobs.md'},
    {id:'jobs.chat-routines', surface:'agent chat and jobs form', component:'wrapper/ui/job-notifications.jsx', api:{tools:'POST /api/routines/tool', notifications:'GET /api/notifications', read:'POST /api/notifications/read', targets:'GET /api/jobs/notification-targets', preference:'POST /api/notifications/preference'}, behavior:'MCP create/list/update/capabilities; one scheduler; durable receipts; existing Telegram and active WhatsApp targets; no mail or closed-browser Web Push; uncertain sends are not retried'},
    {id:'chat.privacy', surface:'per-pane chat menu; chat list; PIN gate', component:'wrapper/ui/chat-privacy.tsx', sources:['core/chat_privacy.py','wrapper/ui/chat-privacy-client.mjs'], api:{status:'GET /api/chat/privacy/status',setup:'POST /api/chat/privacy/setup',unlock:'POST /api/chat/privacy/unlock',lock:'POST /api/chat/privacy/lock',remove:'POST /api/chat/privacy/remove',touch:'POST /api/chat/privacy/touch'}, behavior:'Four-digit PIN; server-checked tab grants; five-minute idle expiry; globally revoked on lock; masked titles; filtered search/events; active memory excluded. Screen privacy, not encryption or user isolation.', contract:'wrapper/surfaces/chat.md'},
    {id:'chat.statistics', version:'1.1.0', surface:'chat start fan and report conversation', component:'wrapper/ui/statistics.tsx', sources:['wrapper/statistics.mjs','wrapper/ui/statistics-data.mjs','wrapper/ui/components/ui/activity-pixels.tsx'], api:{read:'GET /api/statistics',open:'POST /api/statistics/chat'}, behavior:'Workspace-local activity with private chats excluded by core privacy records, honest coverage, deduplicated turns and calendar-day streaks; immutable report chat with period buttons, model distribution and a separately refreshed usage tab; no inference request on open', migration:'Additive optional statisticsTurns and version-1 statisticsSnapshot on chat metadata; old readers retain Markdown report, no destructive migration.', contract:'wrapper/surfaces/chat.md'},
    {id:'chat.allowances',version:'1.0.0',surface:'chat start fan and allowance detail',component:'wrapper/ui/usage.tsx',sources:['wrapper/usage.mjs','wrapper/claude-usage.mjs'],api:{read:'GET /api/usage/allowances'},behavior:'Native account-wide allowance percentages, per-model windows, credits and reset dates; cached independent provider reads without prompts; missing and stale states explicit',migration:'Additive optional turn usage metadata; no destructive migration or credential copy.',contract:'wrapper/surfaces/chat.md'},
    {id:'chat.start', version:'1.4.0', migration:'No persistent data changes; rollback restores the former feed limit and presentation.', sources:['wrapper/ui/reply-card-preview.tsx','wrapper/ui/live-answer-cards-preview.tsx'], surface:'default entry and new chat', component:'wrapper/ui/chat-start.tsx', api:{thread:'GET /api/thread',notifications:'GET /api/notifications',reportChat:'POST /api/planner/chat'}, behavior:'Live per-chat latest unread reply cards without a five-card cap, protected visible-card previews and precise answer navigation; stable selection and insertion order, presence transitions, inert departing cards and reduced motion; contextual greeting and height-aware compact attention fan; persistent weather and local-date calendar shortcuts flank the initial card; calendar opens existing view without claiming external event sync; questions before unread latest routine results and completed chats; starter cards fill the composer only; existing chat and approval routes; configured weather card starts its report and summary on explicit click, other starter cards never auto-send', contract:'wrapper/surfaces/chat.md'},
    {id:'planner.overview', surface:'search and direct links ?view=today or ?view=calendar; legacy pipeline link opens today', component:'wrapper/ui/planner.tsx', selector:'[data-capability="planner.overview"]', api:{schema:'GET /api/crm/schema',crm:'POST /api/crm/query',entity:'GET /api/crm/entities/{entity_id}',notifications:'GET /api/notifications'}, behavior:'Today briefing, agenda, decisions; day/week/month calendar with ISO weeks and optional weekdays; labelled isolated interactive examples, real CRM due steps and existing notifications; no external calendar sync, geolocation, weather fetch or persistent event writes', contract:'docs/PLANNER.md'},
    {id:'chat.model.select', surface:'composer model popover', component:'wrapper/ui/model-picker.jsx', sources:['wrapper/worker-models.mjs','system/worker-catalog.mjs'], api:{activate:'POST /api/workers/activate', create:'POST /api/chats', configure:'POST /api/worker-session', nextTurn:'POST /api/turn', handoff:'POST /api/chat/provider', speed:'POST /api/chat/speed', status:'GET /api/workers'}, behavior:'Explicit Codex/Claude Code selection; native CLI/OAuth auth; no worker restart; GPT-5.6/6 UI filter; exact advertised effort values with a terracotta step slider; per-chat next-turn selections leave active turns unchanged; confirmed ACP configs; explicit provider handoff retains the visible chat and supplies prior context after confirmed cancellation; shared compact picker with native Codex/Claude Fast; idle provider click switches directly without extra activation; bounded handoff includes original objective and recent progress'},
    {id:'inbox.messages', surface:'sidebar above jobs; inbox replaces sidebar with conversation list and back action', component:'wrapper/ui/inbox.tsx', selector:'[data-capability="inbox.messages"]', api:{list:"GET /api/inbox/threads",draft:"POST /api/inbox/draft",status:"GET /api/mail/accounts"}, behavior:"Installation-scoped Gmail/Outlook inbox, durable versioned drafts; existing reply line does not send; explicit sending through shared inbox tools"},
    {id:'chat.fork', version:'1.0.0', surface:'chat menu and assistant message actions', component:'wrapper/ui/app.jsx', sources:['wrapper/server.mjs','wrapper/chat-fork.mjs'], api:{fork:'POST /api/fork',status:'GET /api/chats'}, behavior:'Native fork with persistent family IDs and Roman title prefixes; first fork numbers source I and copy II; nested forks advance the shared sequence; wrapper/chats refreshes all panels', contract:'wrapper/surfaces/chat.md'},
    {id:'chat.message.delivery',version:'1.0.0',surface:'user message receipts and background outbox',component:'wrapper/ui/app.jsx#DeliveryMark',sources:['wrapper/message-delivery.mjs','wrapper/ui/message-outbox.mjs'],api:{accept:'POST /api/delivery',receipt:'GET /api/delivery',chat:'GET /api/deliveries'},behavior:'Durable acceptance before acknowledgement; idempotent request identities; background dispatch independent of selected pane; neutral single/double checks; uncertain native sends are never replayed automatically',migration:'Additive state.messageDelivery version 1 and workspace-scoped browser pending outbox; retain receipts on rollback and drain pending work first.',contract:'wrapper/surfaces/chat.md'},
    {id:'chat.message.edit', surface:'user message actions', component:'wrapper/ui/app.jsx#Item', behavior:'Edit and branch via existing confirmation flow'},
    {id:'chat.message.delete', surface:'user message actions', component:'wrapper/ui/app.jsx#Item', behavior:'Direct delete button opens existing confirmation; disabled during active turn'},
    {id:'chat.message.read-aloud', surface:'final assistant message actions', component:'wrapper/ui/message-speech.tsx', selector:'[data-capability="chat.message.read-aloud"]', playback:'wrapper/ui/speech-playback.mjs', api:{status:'GET /api/speech/status', synthesize:'POST /api/speech/synthesize', settings:'POST /api/speech/settings', voices:'GET /api/speech/voices', connect:'POST /api/speech/connect'}, request:{text:'1–5000 characters; playback chunks at 2000'}, response:{audio:'base64',mime:'audio/wav or audio/mpeg'}, providers:[{id:'local',engine:'Piper',voice:'de_DE-thorsten-high',setup:'npm --prefix wrapper run setup:speech',ready:'localReady'},{id:'elevenlabs',connection:'speech-elevenlabs',ready:'elevenlabs && voiceId && provider === elevenlabs'}], settingsFile:'speech-settings.json under UWE_DATA_ROOT', secrets:'existing core secret store via integrations.mjs; never in this manifest', behavior:'User gesture; final prose only; exclusive playback; stop/unmount cancels; no automatic cloud fallback'},
  ],
};

// Enumerate every literal API declaration from the current source tree, so the
// inventory grows with route modules instead of maintaining a second route list.
export async function inventory(root = fileURLToPath(new URL('../', import.meta.url))) {
  const endpoints = [];
  for(const dir of ['wrapper','core']) {
    for(const file of (await readdir(path.join(root,dir))).sort()) {
      if(!/\.(mjs|py)$/.test(file)) continue;
      const source = `${dir}/${file}`;
      const text = await readFile(path.join(root,source),'utf8');
      const patterns = [ /\broute\(\s*['"](GET|POST|PUT|PATCH|DELETE)['"]\s*,\s*['"]([^'"]+)['"]/g, /@(?:app|router)\.(get|post|put|patch|delete)\(\s*['"]([^'"]+)['"]/g ];
      for(const pattern of patterns) for(const match of text.matchAll(pattern)) endpoints.push({method:match[1].toUpperCase(),path:match[2],source,line:text.slice(0,match.index).split('\n').length});
    }
  }
  return {...capabilities, modules: JSON.parse(await readFile(path.join(root,'system/modules.json'),'utf8')).modules, endpointCoverage:'All literal route(...) and @app/@router.method(...) declarations in wrapper/*.mjs and core/*.py; dynamic routes and external worker tools remain in referenced catalogs.', endpoints};
}
if(process.argv[1] && path.resolve(process.argv[1])===fileURLToPath(import.meta.url)) console.log(JSON.stringify(await inventory(),null,2));
