import React, {useState} from 'react';
import {Modal} from './modal.jsx';
import {SettingRow} from './settings-row.jsx';
import {Plus, Search, ArrowUpRight} from './icons.jsx';
import './pipeline.css';
const stages = ['Lead', 'Angebot', 'Laufend', 'Abgeschlossen'] as const;
type Stage = typeof stages[number];
type Entry = {id:string; title:string; customer:string; stage:Stage; amount:string; next:string; date:string};
const examples:Entry[] = [
 {id:'lead',title:'Bad modernisieren',customer:'Beispielkunde Nord',stage:'Lead',amount:'',next:'Erstgespräch führen',date:'2026-09-10'},
 {id:'offer',title:'Heizung erneuern',customer:'Beispielkunde West',stage:'Angebot',amount:'18500',next:'Angebot nachfassen',date:'2026-09-11'},
 {id:'active',title:'Wartung vereinbaren',customer:'Beispielkunde Süd',stage:'Laufend',amount:'850',next:'Ausführung abstimmen',date:'2026-09-14'},
 {id:'done',title:'Armatur austauschen',customer:'Beispielkunde Ost',stage:'Abgeschlossen',amount:'420',next:'',date:''},
];
const money = (value:string) => value ? new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(value)) : 'Wert offen';
const dateLabel = (value:string) => value ? new Date(value+'T12:00:00').toLocaleDateString('de-DE',{day:'numeric',month:'short'}) : '';
export function PipelineCard({entry,onOpen}:{entry:Entry;onOpen:()=>void}) {
 return <button className="pipeline-card" onClick={onOpen} aria-label={`${entry.title}, ${entry.customer}, ${entry.stage}. Öffnen`}><span className="pipeline-customer">{entry.customer}</span><strong>{entry.title}</strong><span className="pipeline-amount">{money(entry.amount)}</span>{entry.stage !== 'Abgeschlossen' && <span className="pipeline-next"><span>{entry.next}</span><time dateTime={entry.date}>{dateLabel(entry.date)}</time></span>}<ArrowUpRight size={14} strokeWidth={undefined}/></button>;
}
export function PipelinePatternPreview(){return <PipelineCard entry={examples[1]} onOpen={()=>{}}/>;}
type Props = {PageHeading:React.ComponentType<any>;onShowSidebar?:()=>void};
export function PipelinePage({PageHeading,onShowSidebar}:Props){
 const [entries,setEntries]=useState<Entry[]>(examples),[search,setSearch]=useState(''),[concept,setConcept]=useState(false),[draft,setDraft]=useState<Entry|null>(null),[error,setError]=useState('');
 const filtered=entries.filter(e=>(e.title+' '+e.customer).toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const open=(entry:Entry)=>{setError('');setDraft({...entry});};
 const fresh=()=>open({id:crypto.randomUUID(),title:'',customer:'',stage:'Lead',amount:'',next:'',date:''});
 const update=(key:keyof Entry,value:string)=>setDraft(current=>current?{...current,[key]:value}:null);
 const save=(event:React.FormEvent)=>{event.preventDefault();if(!draft)return;if(!draft.title.trim()||!draft.customer.trim()){setError('Bitte Vorgang und Kunde angeben.');return;}if(draft.stage!=='Abgeschlossen'&&(!draft.next.trim()||!draft.date)){setError('Ein offener Vorgang braucht einen nächsten Schritt mit Datum.');return;}setEntries(current=>current.some(e=>e.id===draft.id)?current.map(e=>e.id===draft.id?draft:e):[...current,draft]);setDraft(null);};
 return <div className="page pipeline-page" data-capability="pipeline.preview"><PageHeading title="Pipeline" onShowSidebar={onShowSidebar}><button className="small-button" onClick={()=>setConcept(true)}>Konzept</button><button className="primary small-button" onClick={fresh}><Plus size={16} strokeWidth={undefined}/>Vorgang anlegen</button></PageHeading><div className="pipeline-toolbar"><label className="pipeline-search"><Search size={16} strokeWidth={undefined}/><input type="search" aria-label="Pipeline durchsuchen" placeholder="Kunde oder Vorgang suchen" value={search} onChange={e=>setSearch(e.target.value)}/></label><span className="pipeline-example">Beispieldaten · Entwurf</span></div><div className="pipeline-board">{stages.map(stage=>{const items=filtered.filter(e=>e.stage===stage);return <section className="pipeline-column" key={stage} aria-label={stage}><header><h2>{stage}</h2><span>{items.length}</span></header><div className="pipeline-items">{items.map(entry=><PipelineCard key={entry.id} entry={entry} onOpen={()=>open(entry)}/>)}{!items.length&&<p className="pipeline-empty">{search?'Keine Treffer':'Noch keine Vorgänge'}</p>}</div></section>;})}</div>
 {concept&&<Modal wide={false} title="Die Pipeline" onClose={()=>setConcept(false)}><p>Hier verfolgst du Kunden und Vorgänge von der ersten Anfrage bis zum Abschluss.</p><div className="settings-group"><SettingRow title="Bedienbarer Entwurf" description="Alle Einträge sind erfundene Beispiele. Änderungen gelten nur, solange die Pipeline geöffnet bleibt. Es werden keine Kunden- oder CRM-Daten gespeichert."/><SettingRow title="Ein nächster Schritt" description="Jeder offene Vorgang braucht eine konkrete Aktion mit Datum. Öffne einen Vorgang, um ihn zu bearbeiten oder die Phase zu wechseln."/><SettingRow title="Data arbeitet im Hintergrund" description="Später verbindet die gemeinsame Datenbasis Personen, Firmen, Nachrichten und Workspaces. Externe Systeme werden weiterhin unter Einstellungen → Verbindungen eingerichtet."/><SettingRow title="Neue Nachricht, aktueller Stand" description="Später werden relevante Änderungen mit Quelle geprüft. Unklare Aussagen landen zur Klärung, statt einen Vorgang still zu verändern."/></div><button onClick={()=>{setEntries(examples);setSearch('');setConcept(false)}}>Beispiele zurücksetzen</button></Modal>}
 {draft&&<Modal wide={false} title={entries.some(e=>e.id===draft.id)?'Vorgang bearbeiten':'Vorgang anlegen'} onClose={()=>setDraft(null)}><form className="pipeline-form" onSubmit={save}><label>Vorgang<input required value={draft.title} onChange={e=>update('title',e.target.value)} placeholder="Worum geht es?"/></label><label>Kunde oder Firma<input required value={draft.customer} onChange={e=>update('customer',e.target.value)}/></label><div className="pipeline-form-pair"><label>Phase<select value={draft.stage} onChange={e=>update('stage',e.target.value)}>{stages.map(stage=><option key={stage}>{stage}</option>)}</select></label><label>Wert in Euro<input type="number" min="0" step="0.01" value={draft.amount} onChange={e=>update('amount',e.target.value)} placeholder="Optional"/></label></div>{draft.stage!=='Abgeschlossen'&&<><label>Nächster Schritt<input required value={draft.next} onChange={e=>update('next',e.target.value)} placeholder="Was steht als Nächstes an?"/></label><label>Fällig am<input type="date" required value={draft.date} onChange={e=>update('date',e.target.value)}/></label></>}{error&&<p role="alert">{error}</p>}<p className="pipeline-example">Nur im Entwurf. Keine Änderung an verbundenen Systemen.</p><div className="row"><button type="button" onClick={()=>setDraft(null)}>Abbrechen</button><button type="submit" className="primary">Im Entwurf übernehmen</button></div></form></Modal>}
 </div>;
}
