/** AGENT CI v1.0 — the single source for CSS and the Appearance reference. */
export const identity = {
  name: "AGENT",
  version: "1.0",
  description:
    "Ruhig, klar und persönlich. Warme neutrale Flächen, präzise Typografie und ein neutrale Bedienelemente nach macOS-Vorbild.",
};
export const fonts = [
  {
    name: "System-Serif",
    role: "Antworten des Agenten",
    token: "font-conversation",
    value: 'Charter, "Bitstream Charter", "Sitka Text", Georgia, serif',
    system: true,
    specimen: "Lass uns das gemeinsam anschauen.",
  },
  {
    name: "Inter",
    role: "Oberfläche & Lesetext",
    token: "font-ui",
    value: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    source: "https://github.com/rsms/inter/tree/v4.1",
    license: "Inter-LICENSE.txt",
    specimen: "Ein klarer Gedanke. Ein guter nächster Schritt.",
  },
  {
    name: "IBM Plex Mono",
    role: "Code & technische Werte",
    token: "font-mono",
    value: '"IBM Plex Mono", ui-monospace, monospace',
    source: "https://github.com/IBM/plex",
    license: "IBMPlexMono-LICENSE.txt",
    specimen: "const auftrag = { status: 'bereit' };",
  },
];
export const typography = [
  {
    id: "caption",
    label: "Zusatzinformation",
    size: 12,
    line: 1.5,
    weight: 400,
    use: "Zeitstempel, Zähler, Tastenkürzel",
  },
  {
    id: "small",
    label: "Hilfstext",
    size: 13,
    line: 1.5,
    weight: 400,
    use: "Beschreibungen, Code, Statusdetails",
  },
  {
    id: "control",
    label: "Bedienelement",
    size: 14,
    line: 1.5,
    weight: 500,
    use: "Navigation, Buttons, Formularbeschriftungen",
  },
  {
    id: "body",
    label: "Standardtext",
    size: 15,
    line: 1.5,
    weight: 400,
    use: "Listen und kurze Inhalte",
  },
  {
    id: "reading",
    label: "Lesetext",
    size: 16,
    line: 1.6,
    weight: 400,
    use: "Chat, Antworten, längere Inhalte",
  },
  {
    id: "heading",
    label: "Gruppenüberschrift",
    size: 18,
    line: 1.4,
    weight: 600,
    use: "Zusammengehörige Inhalte",
  },
  {
    id: "subheading",
    label: "Zwischenüberschrift",
    size: 20,
    line: 1.4,
    weight: 600,
    use: "Unterabschnitte in Antworten und Details",
  },
  {
    id: "section",
    label: "Abschnittstitel",
    size: 22,
    line: 1.4,
    weight: 600,
    use: "Hauptabschnitte einer Seite",
  },
  {
    id: "title",
    label: "Seitentitel",
    size: 28,
    line: 1.2,
    weight: 500,
    use: "Eine klare Überschrift pro Seite",
  },
  {
    id: "welcome",
    label: "Begrüßung",
    size: 36,
    line: 1.2,
    weight: 500,
    use: "Persönlicher Einstieg in einen neuen Chat",
  },
  {
    id: "display",
    label: "Große Anzeige",
    size: 48,
    line: 1.2,
    weight: 500,
    use: "Nur für die bestehende Sprachansicht",
  },
];
export const spacing = [2, 4, 8, 12, 16, 20, 24, 28, 32, 40, 48, 64];
export const radii = { small: 4, control: 8, button: 6, panel: 12, large: 24, pill: 999 };
export const controls = { height: "32px", target: "40px", touch: "44px", "heading-height": "52px", "app-heading-height": "84px", "row-height": "48px", "switch-width": "36px", "switch-height": "20px", "switch-thumb": "16px", "switch-travel": "16px" };
export const weights = { regular: 400, medium: 500, semibold: 600, bold: 700 };
export const leading = { tight: 1.2, compact: 1.4, normal: 1.5, reading: 1.6 };
export const themes = {
  dark: {
    'brand-asset-bg': '#ffffff',
    bg: "#1b1a19",
    "workspace-backdrop": "#151413",
    sidebar: "#282725",
    surface: "#252422",
    raised: "#302e2b",
    selected: "#ffffff12",
    border: "#ffffff14",
    text: "#f3f1ed",
    muted: "#b5b0a8",
    faint: "#a39e96",
    accent: "#da977e",
    blue: "#91baff",
    input: "#2c2a27",
    glass: "#302e2b",
    "sheet-glass": "#302e2bb8",
    hover: "#ffffff09",
    composer: "#282725",
    "composer-blur": "#282725b8",
    success: "#8dceb0",
    "switch-thumb": "#ffffff",
    "switch-on": "#858585",
    "switch-off": "#454545",
    "chat-complete": "#25d366",
    "project-red": "#f2a898",
    "project-orange": "#da977e",
    "project-yellow": "#e7c678",
    "project-green": "#8dceb0",
    "project-blue": "#91baff",
    "project-purple": "#c3a4eb",
    "project-pink": "#e9a1c5",
    "avatar-sand": "#514737",
    "avatar-clay": "#593f35",
    "avatar-sage": "#374b40",
    "avatar-sky": "#354857",
    "avatar-lavender": "#48405a",

    warning: "#e7b678",
    danger: "#f2a898",
    "success-bg": "#253a30",
    "warning-bg": "#3a3024",
    "danger-bg": "#402d29",
    "info-bg": "#293344",
    "border-strong": "#716b63",
    "on-primary": "#24221f",
    primary: "#f3f1ed",
    "primary-hover": "#d8d3cb",
    "disabled-bg": "#47433d",
    "selection-color": "#395b85",
    scrollbar: "#77716a",
    overlay: "#00000066",
    shadow: "0 12px 38px #0003, 0 2px 8px #0002",
    "shadow-small": "0 2px 10px #0000000a",
    "shadow-panel-left": "-10px 0 30px #0003",
    "shadow-panel-right": "10px 0 45px #0007",
    "shadow-control": "0 1px 2px #0002",
  },
  light: {
    "workspace-backdrop": "#f7f6f2",
    'brand-asset-bg': '#ffffff',
    bg: "#fcfbf8",
    sidebar: "#f0eee9",
    surface: "#f5f3ee",
    raised: "#e9e6df",
    selected: "#0000000c",
    border: "#00000014",
    text: "#292723",
    muted: "#625e57",
    faint: "#6c665e",
    accent: "#9e513b",
    blue: "#275fab",
    input: "#eeece6",
    glass: "#f5f3ee",
    "sheet-glass": "#f5f3eecc",
    hover: "#00000005",
    composer: "#f0eee9",
    "composer-blur": "#f0eee9c7",
    success: "#226644",
    "switch-thumb": "#ffffff",
    "switch-on": "#686868",
    "switch-off": "#c4c4c4",
    "chat-complete": "#128c45",
    "project-red": "#a13e2c",
    "project-orange": "#9e513b",
    "project-yellow": "#80601c",
    "project-green": "#226644",
    "project-blue": "#275fab",
    "project-purple": "#7950a0",
    "project-pink": "#9a416b",
    "avatar-sand": "#e9dac1",
    "avatar-clay": "#edcbbb",
    "avatar-sage": "#d0decc",
    "avatar-sky": "#cbdfe9",
    "avatar-lavender": "#dcd3ea",

    warning: "#815315",
    danger: "#a13e2c",
    "success-bg": "#e4efe7",
    "warning-bg": "#f5ebd8",
    "danger-bg": "#f7e6e1",
    "info-bg": "#e7edf6",
    "border-strong": "#928a80",
    "on-primary": "#fcfbf8",
    primary: "#292723",
    "primary-hover": "#45413b",
    "disabled-bg": "#e5e1d9",
    "selection-color": "#c6dcf9",
    scrollbar: "#938b7f",
    overlay: "#00000066",
    shadow: "0 12px 38px #00000012, 0 2px 8px #0000000a",
    "shadow-small": "0 2px 10px #0000000a",
    "shadow-panel-left": "-10px 0 30px #00000014",
    "shadow-panel-right": "10px 0 45px #00000018",
    "shadow-control": "0 1px 2px #0002",
  },
};
export const colorRoles = {
  bg: "Hintergrund",
  sidebar: "Seitenleiste",
  surface: "Gruppenfläche",
  raised: "Erhöhte Fläche",
  text: "Haupttext",
  muted: "Sekundärtext",
  faint: "Zusatztext",
  accent: "Markenakzent",
  blue: "Links & Fokus",
  success: "Erfolg",
  warning: "Hinweis",
  danger: "Fehler",
};
export function renderDesignCSS() {
  const shared = Object.fromEntries([
    ...fonts.map((f) => [f.token, f.value]),
    ...typography.map((t) => [`text-${t.id}`, `${t.size / 16}rem`]),
    ...spacing.map((n) => [`space-${n}`, `${n / 16}rem`]),
    ...Object.entries(radii).map(([k, v]) => [`radius-${k}`, `${v}px`]),
    ...Object.entries(controls).map(([k, v]) => [`control-${k}`, v]),
    ...Object.entries(weights).map(([k, v]) => [`weight-${k}`, v]),
    ...Object.entries(leading).map(([k, v]) => [`leading-${k}`, v]),
  ]);
  const rule = (selector, values, mode) =>
    `${selector} {\n${mode ? `  color-scheme: ${mode};\n` : ""}${Object.entries(
      values,
    ).concat(values.muted ? [["select-arrow", `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'%3E%3Cpath d='m4 6 4 4 4-4' fill='none' stroke='${values.muted.replace('#', '%23')}' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E")`]] : [])
      .map(([k, v]) => `  --${k}: ${v};`)
      .join("\n")}\n}\n`;
  return (
    "/* Generated by build.mjs from design-system.mjs. Do not edit. */\n" +
    rule(":root", { ...shared, ...themes.dark }, "dark") +
    rule(':root[data-theme="light"]', themes.light, "light") +
    Object.entries(themes)
      .map(([mode, values]) => rule(`.theme-choice.${mode}`, values, mode))
      .join("")
  );
}
