import React,{useEffect,useState} from 'react';
import {FilterPicker} from './filter-picker.jsx';
import {FileText,Search,RefreshCw,Image,ChevronRight} from './icons.jsx';
import {KnowledgePanel} from './knowledge.tsx';
export function LibraryPage({api,notify,onOpen,onImage,projects,PageHeading,onShowSidebar,revision}) {
  const [section,setSection]=useState('files');
  const [data,setData]=useState({entries:[]}),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[project,setProject]=useState('all'),[busy,setBusy]=useState(true),[error,setError]=useState('');
  async function refresh(){setBusy(true);setError('');try{setData(await api('/library'));}catch(e){setError(e.message);notify(e.message);}finally{setBusy(false);}}
  useEffect(()=>{void refresh();},[revision]);
  const entries=data.entries.filter(e=>(kind==='all'||kind==='favorite'&&e.favorite||e.kind===kind)&&(project==='all'||e.projectId===project)&&`${e.name} ${e.worker||''} ${e.origin||''}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page library-page"><PageHeading title="Bibliothek" onShowSidebar={onShowSidebar}/><div className="knowledge-tabs" aria-label="Bibliotheksansicht"><button aria-pressed={section==='files'} onClick={()=>setSection('files')}>Dateien</button><button aria-pressed={section==='knowledge'} onClick={()=>setSection('knowledge')}>Wissen und Notizen</button></div>{section==='knowledge'?<KnowledgePanel api={api} projects={projects} notify={notify}/>:<><div className="skill-filters"><div className="search-box"><Search size={18}/><input aria-label="Ergebnisse suchen" placeholder="Ergebnisse suchen" value={query} onChange={e=>setQuery(e.target.value)}/></div><FilterPicker label="Dateityp" value={kind} onChange={setKind} options={['all','favorite','image','pdf','text','audio','video','download'].map((v,i)=>({value:v,label:['Alle Dateien','Favoriten','Bilder','PDFs','Text und Code','Audio','Video','Weitere Dateien'][i]}))}/><FilterPicker label="Arbeitsbereich" value={project} onChange={setProject} options={[{value:'all',label:'Alle Arbeitsbereiche'},...projects.map(p=>({value:p.id,label:p.name}))]}/></div>
    <div className="row between library-toolbar"><p className="skill-results-status" role="status">{busy?'Ergebnisse werden geladen …':`${entries.length} Ergebnisse`}</p><div className="row"><button aria-label="Bibliothek aktualisieren" title="Aktualisieren" disabled={busy} onClick={refresh}><RefreshCw size={18}/></button><button onClick={onImage}><Image size={18}/>Bild erstellen</button></div></div>
    {error&&<p role="alert">{error}</p>}{data.truncated&&<p className="page-note">Die erste Erfassung ist auf 5.000 Dateien begrenzt.</p>}{data.warnings?.map(w=><p className="page-note" key={w}>{w}</p>)}
    <div className="integration-grid" aria-busy={busy}>{entries.map(e=><button className="integration-item" key={e.id} onClick={()=>onOpen(e)}><div className="app-icon"><FileText size={24}/></div><div><strong>{e.name}</strong><p>{e.missing?'Datei nicht mehr vorhanden':`${e.origin||'Ergebnis'}${e.worker?' · '+e.worker:''}`}</p></div><ChevronRight size={17}/></button>)}</div>
    {!busy&&!entries.length&&!error&&<div className="empty"><FileText size={28}/><h3>{query||kind!=='all'?'Keine passenden Ergebnisse':'Noch keine Ergebnisse'}</h3><p>Erzeugte Dateien aus Chats und Output-Ordnern erscheinen hier.</p></div>}
  </>}</div>;
}
export function ImageForm({api,connections,projects,projectId,onCreated,Field}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState('');const available=connections.filter(c=>c.provider==='openai-image');
  return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await onCreated(await api('/library/image',Object.fromEntries(f)));}catch(e){setError(e.message);}finally{setBusy(false);}}}>
    {available.length?<><Field label="Bildverbindung"><select name="connectionId">{available.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Arbeitsbereich"><select name="projectId" defaultValue={projectId}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Bildbeschreibung"><textarea name="prompt" required rows={5} maxLength={10000}/></Field><p className="page-note">Verwendet den eingerichteten API-Zugang. Das erzeugte Bild wird im Arbeitsbereich gespeichert.</p><div className="row end"><button disabled={busy} className="primary">{busy?'Bild wird erzeugt …':'Bild erzeugen'}</button></div></>:<p>Bitte zuerst unter Verbindungen einen OpenAI-Bildzugang einrichten. Vorhandene Bildwerkzeuge eines Workers bleiben im Chat nutzbar.</p>}{error&&<p role="alert">{error}</p>}
  </form>;
}
