import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import path from 'node:path';
import net from 'node:net';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn) {for(let i=0;i<200;i++){const value=await fn();if(value)return value;await delay(25);}throw Error('Timed out');}
test('Workspace HTTP preserves native chats and reads the latest specialization on every turn', {timeout:30000}, async t=>{
  const dir=await mkdtemp(path.join(root,'.verify-workspaces-http-'));
  const reservation=net.createServer().listen(0,'127.0.0.1');await once(reservation,'listening');const port=reservation.address().port;await new Promise(r=>reservation.close(r));
  let child,exit,token,logs='';const base=`http://127.0.0.1:${port}/api`, state=path.join(dir,'worker.json');
  const get=async route=>{const r=await fetch(base+route);if(!r.ok)throw Error(await r.text());return r.json();};
  const post=async(route,body)=>{const r=await fetch(base+route,{method:'POST',headers:{'content-type':'application/json','x-uwe-token':token},body:JSON.stringify(body)});const result=await r.json();assert.equal(r.status,200,JSON.stringify(result));return result;};
  const binary=path.join(dir,'worker.mjs');
  await writeFile(binary, '#!'+process.execPath+'\n'+(await readFile(path.join(root,'wrapper/test/message-delivery-worker.fixture.mjs'),'utf8')).replace(/^#![^\n]*\n/,'').replace('process.env.DELIVERY_FIXTURE_STATE',JSON.stringify(state)),{mode:0o700});
  const start=async()=>{
    child=spawn(process.execPath,['wrapper/server.mjs'],{cwd:root,env:{...process.env,AGENT_CORE_URL:'',COMPANY_BASE:path.join(root,'firmenbasis'),SYSTEM_BASE:path.join(root,'system'),UWE_CODEX_SOURCE_HOME:'',UWE_PORT:String(port),UWE_WORKSPACE:path.join(dir,'workspace'),UWE_DATA_ROOT:path.join(dir,'control'),UWE_CODEX_BINARY:binary,DELIVERY_FIXTURE_STATE:state},stdio:['ignore','pipe','pipe']});exit=once(child,'exit');child.stderr.on('data',b=>logs+=b);child.stdout.on('data',b=>logs+=b);
    await until(async()=>{if(child.exitCode!==null)throw Error(logs);try{return await get('/chats');}catch{return false;}});token=(await get('/bootstrap')).token;
  };
  const stop=async()=>{child.kill();await exit;};
  t.after(async()=>{if(child?.exitCode===null)await stop();await rm(dir,{recursive:true,force:true});});
  await start();
  const beforeChats=(await get('/chats')).chats.length;
  const payload={requestId:'simple-workspace-create',name:'Simple area',description:'Optional scope',icon:'globe',color:'blue'};
  const [created,retried]=await Promise.all([post('/projects/save',payload),post('/projects/save',payload)]);
  assert.equal(created.project.id,retried.project.id);
  assert.equal((await get('/chats')).chats.length,beforeChats,'creation must not start a setup chat');
  const simple=await get('/workspaces/definition?id='+created.project.id);
  assert.equal(simple.profile.status,'ready');assert.equal(simple.profile.description,'Optional scope');
  assert.equal(simple.profile.icon,'globe');assert.equal(simple.profile.color,'blue');
  assert.doesNotMatch(simple.body,/Offene Punkte|Einrichtungsgespräch/);
  await post('/workspaces/save',{id:created.project.id,revision:simple.revision,name:'Renamed area',description:'',icon:'files',color:'green'});
  const renamed=await get('/workspaces/definition?id='+created.project.id);
  assert.equal(renamed.body,simple.body);assert.equal(renamed.profile.status,'ready');
  assert.equal(renamed.project.path,simple.project.path);assert.equal(renamed.profile.name,'Renamed area');
  await post('/workers/connect',{id:'codex'});
  const origin=base.slice(0,-4),html=await(await fetch(origin+'/')).text();
  const assets=[...new Set([...html.matchAll(/(?:src|href)="(\/[^"?#]+)"/g)].map(match=>match[1]))];
  assert.ok(assets.some(asset=>asset.startsWith('/assets/')&&asset.endsWith('.js')),'production chunks must be included');
  for(const asset of assets){
    const response=await fetch(origin+asset);assert.equal(response.status,200,asset);
    if(asset.endsWith('.js'))assert.match(response.headers.get('content-type'),/javascript/);
    assert.deepEqual(Buffer.from(await response.arrayBuffer()),await readFile(path.join(root,'wrapper/dist',asset.slice(1))),asset);
  }
  for(const missing of ['/assets/missing.js','/%2e%2e/package.json','/assets/%2e%2e/%2e%2e/package.json'])assert.equal((await fetch(origin+missing)).status,404,missing);
  assert.equal((await get('/bootstrap')).features.workspaceSpecialization,true);
  const [one,two]=await Promise.all([post('/workspaces/chat',{requestId:'http-onboarding'}),post('/workspaces/chat',{requestId:'http-onboarding'})]);
  assert.equal(one.thread.id,two.thread.id);const id=one.thread.id,project=one.project;
  await until(async()=>!(await get('/chats')).active?.[id]);
  let disk=JSON.parse(await readFile(state,'utf8'));
  assert.equal(Object.keys(disk.threads).length,1);
  let instructions=disk.calls.at(-1).params.collaborationMode.settings.developer_instructions;
  assert.match(instructions,/Workspace-Einrichtung/);assert.match(instructions,/dieselbe|derselbe/);
  const definition=await get('/workspaces/definition?id='+project.id);
  await post('/workspaces/save',{id:project.id,revision:definition.revision,name:'Special reports',description:'Review input documents',status:'ready',body:'# Special rule\n\nAlways separate sources from assumptions.\n'});
  await post('/turn',{id,text:'Please prepare a report.'});
  await until(async()=>!(await get('/chats')).active?.[id]);
  disk=JSON.parse(await readFile(state,'utf8'));instructions=disk.calls.at(-1).params.collaborationMode.settings.developer_instructions;
  assert.match(instructions,/Always separate sources from assumptions/);
  assert.match(instructions,/Workspace-Einrichtung/);
  const file=path.join(dir,'workspace',project.path,'AGENTS.md');
  await writeFile(file,(await readFile(file,'utf8')).replace('Special reports','Updated reports').replace('Always separate sources from assumptions.','Read the linked skill only when needed.'));
  assert.equal((await get('/workspaces')).projects.find(p=>p.id===project.id).name,'Updated reports');
  await post('/turn',{id,text:'Continue with the updated rules.'});
  await until(async()=>!(await get('/chats')).active?.[id]);
  disk=JSON.parse(await readFile(state,'utf8'));assert.match(disk.calls.at(-1).params.collaborationMode.settings.developer_instructions,/Read the linked skill only when needed/);
  assert.equal((await get('/workspaces')).projects.find(p=>p.id===project.id).path,project.path);
  const stale=await fetch(base+'/workspaces/save',{method:'POST',headers:{'content-type':'application/json','x-uwe-token':token},body:JSON.stringify({id:project.id,revision:definition.revision,name:'Stale overwrite'})});assert.equal(stale.ok,false);
  await post('/jobs/save',{id:'workspace-report',name:'Workspace report',category:'Independent category',instructions:'Use the selected specialization and report.',projectId:project.id,worker:'codex',status:'paused',schedule:{type:'manual'}});
  const run=await post('/jobs/run',{id:'workspace-report'});
  await until(async()=>!(await get('/chats')).active?.[run.threadId]);
  disk=JSON.parse(await readFile(state,'utf8'));
  assert.match(disk.calls.at(-1).params.collaborationMode.settings.developer_instructions,/Read the linked skill only when needed/);
  assert.doesNotMatch(disk.calls.at(-1).params.collaborationMode.settings.developer_instructions,/Workspace-Einrichtung/);
  assert.ok(disk.threads[run.threadId].cwd.endsWith('/jobs/workspace-report'));
  assert.equal((await get('/jobs')).find(j=>j.id==='workspace-report').category,'Independent category');
  const calls=disk.calls.length;
  await stop();await start();
  assert.equal((await post('/workspaces/chat',{requestId:'http-onboarding'})).thread.id,id);
  disk=JSON.parse(await readFile(state,'utf8'));assert.equal(disk.calls.length,calls);
  assert.equal((await get('/bootstrap')).projects.find(p=>p.id===project.id).name,'Updated reports');
});
